language: R
sudo: false
cache: packages
r:
- oldrel
- release
- devel
r_github_packages:
- jimhester/covr
after_success:
- Rscript -e 'library(covr);codecov()'
- Rscript -e 'covr::coveralls()'
branches:
  only:
  - master
env:
  global:
    secure: xTctNocqbZA1/fFIjPqZ3QyqQ8NxCootvoHCx2spAKsM5Evfbnk7GxNZsFlcf0tHOKpDZm/Fg+oIeH+vDkEKNLm4V6EaTir4vgyS2FOlVT0UAZC0BfFIK1ByCVpmGv4ih2G+CfDeXPab5WX2/2gquZSBuTOJ1VPhukEL2RAtSRjVAV2dyUkgLwLcrDDtcS9ds+ys0ouYF+Hfpaz+xxQOWRXz7Vg7c3o81733FJjdN3pIvmP/k6Pox6p3AmdIEOItTj2NybpydVhVgS+LNEu5n7HZ3OcUIYqfSzCSqnWmoN6uG2y6AWP7r8UdvGyvg+2oTYpmzqfoBEtmRf3cDKsyUMLP+E4nKL1fCMJQmljlgeGSm/cLBLVEhNY4EtrP9UkH/cuBh9xbd3wiUOpMBfza7cmCx5C2P8EGfS1EiWGpp897pnCdZzBeR4w6qcmrDtKFMXDJY1zx8ZLTHDfwnKwQ1fTWwoCJ3xvqeYFRz0psnTWuo+rddiEu/PpGaMVRqe57QiMiG0fStI+3HNkdGqH9Yt3MJ/KAQfs5dkmKU4VyRfoKcE9gaFmh7C+X+GwZZw9VdHdGL26IE4HrPmNMDvPrDhwNVjqEp1+A5bDquBx7atotSfubj6YMcpBAQguoWC1/xRYkv382V/OvJhlNv2TW3fAjDuU8DrwY8kfnAmZjpiE=
